### ISSUE TITLE
code syntax error

### ISSUE THREAD

**Issue by CallMeJai** [caelinsutch/rovotics-cli#1]
upon running rovotics-cli with any arguments:

> /usr/local/lib/node_modules/Rovotics/index.js:6
>     let cmd = args._[0] || 'help';
>     ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/Rovotics/bin/rovotics:2:1)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>

**Comment by caelinsutch** [comment]
Command not replicable on my machine? I'm going to resolve it.
